"""
AI-Code Detection Module
=========================

Detects code that was *probably* generated by an LLM (ChatGPT, Copilot, Claude,
etc.) and flags the structural / stylistic problems that AI-written code tends to
carry into a codebase. For each finding it produces a concrete, "write it cleaner"
suggestion that a real reviewer would leave on a pull request.

This is NOT a plagiarism or academic-integrity tool. It is a maintainability tool:
AI-generated code frequently ships with over-commenting, defensive boilerplate,
placeholder logic, generic naming, and redundant try/except scaffolding. Those
patterns are cheap to detect statically and expensive to leave in a real codebase.

The detector returns:
  - an overall `ai_likelihood` score in [0, 1] with a human-readable band
  - the individual weighted signals that produced that score (explainable)
  - a list of concrete `findings`, each with a line range, severity, an
    explanation, and a cleaner-rewrite suggestion.

Everything here is deterministic, dependency-free (std-lib `ast` + `re`), and runs
per-file so it can scale to large repositories.
"""

import ast
import re
import math
from typing import Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Signal catalogue. Each signal has a weight; the weighted, saturated sum gives
# the AI-likelihood score. Weights were tuned so that no single signal can push
# a file past the "likely" band on its own — AI code is identified by a
# *combination* of tells, exactly like a human reviewer would judge it.
# ---------------------------------------------------------------------------

SIGNAL_WEIGHTS = {
    'explanatory_comment_ratio': 0.22,   # AI narrates every line
    'restating_comments': 0.18,          # "# increment counter" above counter += 1
    'placeholder_logic': 0.20,           # pass / ... / "your code here" / TODO stubs
    'generic_naming': 0.12,              # data, result, temp, foo, my_function
    'defensive_boilerplate': 0.14,       # try/except around trivial code, blanket Exception
    'uniform_structure': 0.08,           # every function same shape: docstring + body + return
    'redundant_type_echo': 0.06,         # docstring/comment repeats the type annotation
}

# Comments that merely restate the line below them. We detect "verb the noun"
# narration that mirrors an assignment or call.
RESTATE_PATTERNS = [
    re.compile(r'(?:#|//|/\*|\*)\s*(initialize|init|create|define|set(?:\s+up)?|declare)\b', re.I),
    re.compile(r'(?:#|//|/\*|\*)\s*(increment|decrement|add|append|push|loop|iterate|store)\b', re.I),
    re.compile(r'(?:#|//|/\*|\*)\s*(return|print|call|import|check if|get the|the final)\b', re.I),
    re.compile(r'(?:#|//|/\*|\*)\s*(this (?:function|method)|here we|now we|first,|next,|finally,|then we)\b', re.I),
]

PLACEHOLDER_PATTERNS = [
    re.compile(r'#\s*(your code here|implement(?:ation)? (?:here|goes here)|todo|fixme|placeholder)', re.I),
    re.compile(r'#\s*\.\.\.\s*$'),
    re.compile(r'\b(raise\s+NotImplementedError)\b'),
    re.compile(r'#\s*(add (?:your )?logic|fill in|complete the)', re.I),
]

# Names that AI reaches for when it has nothing specific to call something.
GENERIC_NAMES = {
    'data', 'result', 'results', 'temp', 'tmp', 'val', 'value', 'values',
    'item', 'items', 'obj', 'object', 'arr', 'lst', 'output', 'input',
    'foo', 'bar', 'baz', 'res', 'ret', 'var', 'x', 'y', 'z',
    'my_function', 'my_func', 'process_data', 'do_something', 'handle',
    'helper', 'utility', 'func', 'function', 'method', 'thing', 'stuff',
}

# Phrasing that shows up in AI docstrings far more than human ones.
AI_DOCSTRING_TELLS = [
    re.compile(r'\bthis (?:function|method|class) (?:is (?:used to|designed to)|takes|will|returns)\b', re.I),
    re.compile(r'\b(?:args?|parameters?):\s*$', re.I),
    re.compile(r'\bthe (?:given|provided|input|specified)\b', re.I),
    re.compile(r'\bwe (?:then|first|now|next)\b', re.I),
    re.compile(r'\bnote that\b', re.I),
    re.compile(r'\bin (?:this|the following) (?:example|case)\b', re.I),
]


class AICodeDetector:
    """Static detector for probable AI-generated Python."""

    BANDS = [
        (0.75, 'very_likely', 'Strongly resembles AI-generated code'),
        (0.50, 'likely', 'Several patterns typical of AI-generated code'),
        (0.30, 'possible', 'A few AI-style patterns present'),
        (0.0,  'unlikely', 'Reads as hand-written code'),
    ]

    def analyze(self, source_code: str, language: str = 'Python') -> Dict:
        """Entry point. Only Python gets full AST treatment; other languages
        fall back to the regex-based stylistic signals."""
        lines = source_code.split('\n')
        n_lines = max(len([l for l in lines if l.strip()]), 1)

        if language == 'Python':
            signals, findings = self._analyze_python(source_code, lines, n_lines)
        else:
            signals, findings = self._analyze_generic(source_code, lines, n_lines)

        score, contributions = self._aggregate(signals)
        band, band_label, band_desc = self._band(score)

        return {
            'ai_likelihood': round(score, 3),
            'band': band,
            'band_label': band_label,
            'band_description': band_desc,
            'signals': contributions,
            'findings': sorted(findings, key=lambda f: f['line_start']),
            'finding_count': len(findings),
            'analyzed_lines': n_lines,
        }

    # ------------------------------------------------------------------
    # Python path
    # ------------------------------------------------------------------
    def _analyze_python(self, source: str, lines: List[str], n_lines: int):
        signals = {k: 0.0 for k in SIGNAL_WEIGHTS}
        findings: List[Dict] = []

        # --- comment-based signals (lexical, no AST needed) ---
        comment_lines = []
        for i, raw in enumerate(lines):
            stripped = raw.strip()
            if stripped.startswith('#'):
                comment_lines.append((i + 1, stripped))

        # explanatory comment density
        comment_ratio = len(comment_lines) / n_lines
        # AI tends toward 1 comment per ~3 code lines; humans ~1 per 8-15.
        signals['explanatory_comment_ratio'] = self._sat(comment_ratio / 0.30)

        # restating comments
        restate_hits = 0
        for ln, text in comment_lines:
            if any(p.search(text) for p in RESTATE_PATTERNS):
                # confirm the next non-blank line is actually trivial code
                nxt = self._next_code_line(lines, ln)
                if nxt and len(nxt.strip()) < 60:
                    restate_hits += 1
                    findings.append(self._finding(
                        'restating_comment', ln, ln, 'low',
                        "Comment restates what the code already says.",
                        "Delete the comment — the code below is self-explanatory. "
                        "Reserve comments for *why*, not *what*.",
                        snippet=text,
                    ))
        signals['restating_comments'] = self._sat(restate_hits / max(n_lines / 12, 1))

        # placeholder logic
        placeholder_hits = 0
        for i, raw in enumerate(lines):
            for p in PLACEHOLDER_PATTERNS:
                if p.search(raw):
                    placeholder_hits += 1
                    findings.append(self._finding(
                        'placeholder_logic', i + 1, i + 1, 'high',
                        "Placeholder / stub left in the code.",
                        "Replace the stub with a real implementation, or remove the "
                        "function until it's needed. Shipping stubs hides missing "
                        "behaviour behind code that looks finished.",
                        snippet=raw.strip(),
                    ))
                    break
        signals['placeholder_logic'] = self._sat(placeholder_hits / 2.0)

        # --- AST-based signals ---
        try:
            tree = ast.parse(source)
        except SyntaxError:
            # still return what the lexical signals found
            return signals, findings

        # generic naming
        generic_hits = 0
        named = 0
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                named += 1
                if node.name.lower() in GENERIC_NAMES:
                    generic_hits += 1
                    findings.append(self._finding(
                        'generic_naming', node.lineno, node.lineno, 'medium',
                        f"Function name '{node.name}' is generic.",
                        f"Rename '{node.name}' to describe what it does, e.g. a verb "
                        f"phrase like 'parse_invoice' or 'fetch_user'. Generic names "
                        f"force readers to read the body to learn the intent.",
                    ))
            elif isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
                named += 1
                if node.id.lower() in GENERIC_NAMES and len(node.id) > 1:
                    generic_hits += 1
        signals['generic_naming'] = self._sat(generic_hits / max(named * 0.35, 1))

        # defensive boilerplate: bare/blanket except, try around 1-2 trivial stmts
        boiler_hits = 0
        for node in ast.walk(tree):
            if isinstance(node, ast.Try):
                body_size = len(node.body)
                for handler in node.handlers:
                    is_blanket = (handler.type is None or
                                  (isinstance(handler.type, ast.Name) and
                                   handler.type.id in ('Exception', 'BaseException')))
                    silent = (len(handler.body) == 1 and
                              isinstance(handler.body[0], ast.Pass))
                    if is_blanket and (silent or body_size <= 2):
                        boiler_hits += 1
                        sev = 'high' if silent else 'medium'
                        msg = ("Bare/blanket exception handler swallows errors."
                               if silent else
                               "try/except wraps trivial code with a blanket catch.")
                        sug = ("Catch the specific exception you expect and handle it "
                               "(log, recover, or re-raise). A blanket 'except: pass' "
                               "hides real bugs."
                               if silent else
                               "Catch a specific exception type. Blanket 'except "
                               "Exception' around two lines usually means the failure "
                               "mode wasn't thought through.")
                        findings.append(self._finding(
                            'defensive_boilerplate', node.lineno,
                            getattr(node, 'end_lineno', node.lineno), sev, msg, sug,
                        ))
        signals['defensive_boilerplate'] = self._sat(boiler_hits / 1.5)

        # uniform structure: many functions share the exact shape
        # (docstring -> single loop/branch -> return). Measured by variance of a
        # cheap structural fingerprint across functions.
        fingerprints = []
        ai_docstring_hits = 0
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                doc = ast.get_docstring(node)
                fp = (
                    1 if doc else 0,
                    sum(1 for n in node.body if isinstance(n, (ast.For, ast.While))),
                    sum(1 for n in node.body if isinstance(n, ast.If)),
                    1 if any(isinstance(n, ast.Return) for n in node.body) else 0,
                )
                fingerprints.append(fp)
                if doc:
                    if any(p.search(doc) for p in AI_DOCSTRING_TELLS):
                        ai_docstring_hits += 1
                    # redundant type echo: docstring re-states annotation types
                    if node.args.args and re.search(r'\b(int|str|float|bool|list|dict)\b', doc, re.I):
                        annotated = any(a.annotation is not None for a in node.args.args)
                        if annotated:
                            signals['redundant_type_echo'] = min(
                                1.0, signals['redundant_type_echo'] + 0.34)
        if len(fingerprints) >= 3:
            # fraction of functions sharing the single most common fingerprint
            from collections import Counter
            common = Counter(fingerprints).most_common(1)[0][1]
            uniformity = common / len(fingerprints)
            signals['uniform_structure'] = self._sat((uniformity - 0.4) / 0.5)
        if ai_docstring_hits:
            findings.append(self._finding(
                'ai_docstring', 0, 0, 'low',
                f"{ai_docstring_hits} docstring(s) use AI-tutorial phrasing "
                f"(\"This function takes…\", \"we then…\").",
                "Rewrite docstrings to state the contract concisely: what it returns "
                "and any non-obvious behaviour. Drop tutorial narration.",
            ))

        return signals, findings

    # ------------------------------------------------------------------
    # Generic (non-Python) path — lexical signals only
    # ------------------------------------------------------------------
    def _analyze_generic(self, source: str, lines: List[str], n_lines: int):
        signals = {k: 0.0 for k in SIGNAL_WEIGHTS}
        findings: List[Dict] = []

        comment_re = re.compile(r'^\s*(//|/\*|\*|#)')
        comment_lines = [(i + 1, l.strip()) for i, l in enumerate(lines)
                         if comment_re.match(l)]
        signals['explanatory_comment_ratio'] = self._sat(
            (len(comment_lines) / n_lines) / 0.30)

        restate_hits = 0
        for ln, text in comment_lines:
            if any(p.search(text) for p in RESTATE_PATTERNS):
                restate_hits += 1
                findings.append(self._finding(
                    'restating_comment', ln, ln, 'low',
                    "Comment restates the code below it.",
                    "Remove narration comments; keep comments for intent and edge cases.",
                    snippet=text,
                ))
        signals['restating_comments'] = self._sat(restate_hits / max(n_lines / 12, 1))

        placeholder_hits = 0
        for i, raw in enumerate(lines):
            for p in PLACEHOLDER_PATTERNS:
                if p.search(raw):
                    placeholder_hits += 1
                    findings.append(self._finding(
                        'placeholder_logic', i + 1, i + 1, 'high',
                        "Placeholder / stub left in the code.",
                        "Replace the stub with a real implementation before merging.",
                        snippet=raw.strip(),
                    ))
                    break
        signals['placeholder_logic'] = self._sat(placeholder_hits / 2.0)

        # generic identifiers in declarations
        decl_re = re.compile(
            r'\b(?:function|const|let|var|def|int|float|double|String|auto)\s+(\w+)')
        generic_hits, named = 0, 0
        for m in decl_re.finditer(source):
            named += 1
            if m.group(1).lower() in GENERIC_NAMES:
                generic_hits += 1
        signals['generic_naming'] = self._sat(generic_hits / max(named * 0.35, 1))

        # defensive boilerplate: empty catch blocks, catch-all handlers
        boiler = 0
        for i, raw in enumerate(lines):
            s = raw.strip()
            if re.search(r'\bcatch\s*\([^)]*\)\s*\{?\s*$', s) or re.search(r'\bcatch\b.*\{\s*\}', s):
                # look ahead for an empty / pass-through body
                nxt = lines[i + 1].strip() if i + 1 < len(lines) else ''
                if nxt in ('}', '') or nxt.startswith('//') or 'pass' in nxt:
                    boiler += 1
            if re.search(r'except\s*:', s) or re.search(r'except\s+Exception', s):
                boiler += 1
        signals['defensive_boilerplate'] = self._sat(boiler / 1.5)

        # uniform structure: many functions opening with a narration comment
        # immediately under the signature (a strong LLM tell across languages)
        func_re = re.compile(r'\b(?:function|def|public|private|static|void|int|String)\b.*[\({]')
        narrated = 0
        funcs = 0
        for i, raw in enumerate(lines):
            if func_re.search(raw) and ('(' in raw):
                funcs += 1
                # check the next non-blank line for a comment
                for j in range(i + 1, min(i + 3, n_lines)):
                    nl = lines[j].strip()
                    if not nl:
                        continue
                    if nl.startswith(('//', '#', '/*', '*', '"""')):
                        narrated += 1
                    break
        if funcs >= 2:
            signals['uniform_structure'] = self._sat(narrated / funcs)

        return signals, findings

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------
    @staticmethod
    def _sat(x: float) -> float:
        """Saturating squash into [0, 1] so any single raw ratio is bounded."""
        if x <= 0:
            return 0.0
        return 1.0 - math.exp(-1.4 * x)

    def _aggregate(self, signals: Dict[str, float]):
        contributions = []
        total = 0.0
        for name, weight in SIGNAL_WEIGHTS.items():
            raw = signals.get(name, 0.0)
            contrib = raw * weight
            total += contrib
            contributions.append({
                'name': name,
                'label': name.replace('_', ' ').title(),
                'strength': round(raw, 3),
                'weight': weight,
                'contribution': round(contrib, 4),
            })
        # normalise by max possible (sum of weights) so score maps to [0,1]
        max_total = sum(SIGNAL_WEIGHTS.values())
        score = total / max_total
        contributions.sort(key=lambda c: c['contribution'], reverse=True)
        return min(score, 1.0), contributions

    def _band(self, score: float):
        for threshold, key, desc in self.BANDS:
            if score >= threshold:
                return key, key.replace('_', ' ').title(), desc
        return 'unlikely', 'Unlikely', 'Reads as hand-written code'

    @staticmethod
    def _next_code_line(lines: List[str], after_line_1based: int) -> Optional[str]:
        for j in range(after_line_1based, len(lines)):
            s = lines[j].strip()
            if s and not s.startswith('#'):
                return lines[j]
        return None

    @staticmethod
    def _finding(kind, line_start, line_end, severity, description, suggestion,
                 snippet=''):
        return {
            'kind': kind,
            'line_start': line_start,
            'line_end': line_end,
            'severity': severity,
            'description': description,
            'suggestion': suggestion,
            'snippet': snippet[:120],
        }
